In [11]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_pickle('budget_by_genre.pkl')

df.head()
exploded_df = df.explode('genre_list')
exploded_df.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,year,domestic_profit,worldwide_profit,domestic_roi,worldwide_roi,tconst,primary_title,original_title,start_year,runtime_minutes,genres,genre_list
0,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000.0,241063875.0,1.045664e+09,2011,-169536125.0,635063875.0,0.587101,2.546673,tt1298650,Pirates of the Caribbean: On Stranger Tides,Pirates of the Caribbean: On Stranger Tides,2011,136.0,"Action,Adventure,Fantasy",Action
0,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000.0,241063875.0,1.045664e+09,2011,-169536125.0,635063875.0,0.587101,2.546673,tt1298650,Pirates of the Caribbean: On Stranger Tides,Pirates of the Caribbean: On Stranger Tides,2011,136.0,"Action,Adventure,Fantasy",Adventure
0,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000.0,241063875.0,1.045664e+09,2011,-169536125.0,635063875.0,0.587101,2.546673,tt1298650,Pirates of the Caribbean: On Stranger Tides,Pirates of the Caribbean: On Stranger Tides,2011,136.0,"Action,Adventure,Fantasy",Fantasy
1,3,"Jun 7, 2019",Dark Phoenix,350000000.0,42762350.0,1.497624e+08,2019,-307237650.0,-200237650.0,0.122178,0.427892,tt6565702,Dark Phoenix,Dark Phoenix,2019,113.0,"Action,Adventure,Sci-Fi",Action
1,3,"Jun 7, 2019",Dark Phoenix,350000000.0,42762350.0,1.497624e+08,2019,-307237650.0,-200237650.0,0.122178,0.427892,tt6565702,Dark Phoenix,Dark Phoenix,2019,113.0,"Action,Adventure,Sci-Fi",Adventure

In [8]:
df.genres.value_counts().head(20)

Drama                         68
Adventure,Animation,Comedy    67
Comedy                        56
Comedy,Drama,Romance          52
Action,Adventure,Sci-Fi       52
Comedy,Drama                  49
Comedy,Romance                41
Action,Crime,Drama            39
Documentary                   36
Drama,Romance                 34
Action,Comedy,Crime           32
Action,Adventure,Fantasy      31
Horror,Mystery,Thriller       31
Action,Adventure,Drama        28
Drama,Thriller                25
Horror,Thriller               24
Action,Crime,Thriller         23
Crime,Drama,Thriller          22
Action,Adventure,Comedy       22
Biography,Drama,History       20
Name: genres, dtype: int64

In [15]:
genre_cats = exploded_df.genre_list.value_counts().head(13)

In [32]:
# plt.scatter(exploded_df.year, exploded_df.worldwide_profit, s=exploded_df.production_budget, c=exploded_df.genre_list)
# plt.show()
g = sns.scatterplot(y="year", x="worldwide_profit",
                    data=exploded_df[exploded_df.genre_list.isin(genre_cats.index)],
                    hue='genre_list', size="production_budget",
                    size_norm=1000000)
g.legend(loc='lower right')

ValueError: ``size_norm`` must be None, tuple, or Normalize object.